### ISSUE TITLE
Set up Travis

### ISSUE THREAD

**Issue by bandali** [ChrisPenner/SitePipe#10]
We could use [hvr/multi-ghc-travis](https://github.com/hvr/multi-ghc-travis) to easily test the build across multiple GHC versions.

**Comment by ChrisPenner** [comment]
Done in 1781adafb3f9dbea6a6c786cba0fbd6d71a85dc7; I've added builds for `GHC-8.0.2` and  `GHC-8.2.1`; let me know if I should throw any others in there 😁
