### ISSUE TITLE
multiple tag types

### ISSUE THREAD

**Issue by hxrts** [ChrisPenner/SitePipe#12]
Hey, great project. I love how compact the code is. Wonder if multiple tag "types" is something that might be of interest. For instance an "author" could be a tag type, and pages could be tagged with one or more authors, this would give a way to differentiate an author from a topical tag.

**Comment by ChrisPenner** [comment]
Yup! This sort of thing is definitely possible; Posts are just collections of meta-data, so if you set an `author: ["George", "Susan"]` property in your header yaml you can pull these off of posts and do anything you like!

You can see the code for `getTags` [here](https://github.com/ChrisPenner/SitePipe/blob/master/src/SitePipe/Utilities.hs#L24-L37); it's relatively simple. You can probably adapt it into a `getAuthors` function without too much trouble.

The whole philosophy of SitePipe is freeing the data for you to do whatever you like :)

**Comment by hxrts** [comment]
My thinking exactly. If I find some time, I may try a PR.

**Comment by ChrisPenner** [comment]
If you end up getting something working I'd suggest you actually write it as combinators which can be a separate library. It'd be nice to have several small extension libraries which export functions of `Value -> Value` and can be mixed and matched easily. Looking forward to seeing what you come up with; but closing this for now.
