### ISSUE TITLE
ResourceLoader does not accept other than String

### ISSUE THREAD

**Issue by ProofOfPizza** [ChrisPenner/SitePipe#16]
Would be nice to use the resource loader to load images and so on. At least to get the urls and such. Now it is restricted to a Reader with type String -> IO String. It would be nice if this was somewhat more forgiving or if another resourceLoader was added. Thx!

**Comment by ChrisPenner** [comment]
For the particular issue you mentioned (getting the urls of copied over files) the new `0.3.0.0` update should help out; `copyFiles` now returns `Value` objects with the src file path and url of the copied files.

Let me know if it does the trick for you or not 😄 
http://hackage.haskell.org/package/sitepipe-0.3.0.0

**Comment by ProofOfPizza** [comment]
Hi Chris, I think this should do exactly what I need. I just could use a pointer to make it work. What I would like is to transform this [Value] into my custom type [Image] so that I can compose it. Writing it directly obviously does not work because the whole list does not have a url along with it. The types I use are like so : 

    data Image = Image {src :: String, url :: String} deriving (Generic)
    data ImageGallery = ImageGallery { name :: String, images :: [Image], url :: String} deriving (Generic)
    data ImageGalleries = ImageGalleries { galleries :: [ImageGallery], url :: String } deriving (Generic)
    instance ToJSON ImageGalleries
    instance ToJSON ImageGallery
    instance ToJSON Image
    instance FromJSON Image

Then inside the IO function:

    images' <- copyFiles ["images/gallery/gal1"]
    let images'' = map fromJSON images' :: [Image]

However this part does not work for me. Maybe I have to write some custom implementation for fromJson ? Or is that Value type not really a json? Any help here appreciated and thanks already!

**Comment by ChrisPenner** [comment]
Looks like it should be working, Value does implement JSON yup;

Can you post the error please? Also make sure you've added a constraint to your cabal file to ensure you're getting the latest sitepipe: sitepipe >= 0.3

**Comment by ProofOfPizza** [comment]
The result I am getting is seems to say it expects some other (intermediate? ) type. I have tried looking at the types and implementations for fromJson in your code but I could not understand all of it yet.
This is what it tells me : 

    • Couldn't match type ‘Result a0’ with ‘Image’
      Expected type: [Image]
        Actual type: [Result a0]
    • In the expression: (map fromJSON images') :: [Image]
      In an equation for ‘images''’:
          images'' = (map fromJSON images') :: [Image]
      In the second argument of ‘($)’, namely
        ‘do { pages <- resourceLoader markdownReader ["*.md"];
              images' <- copyFiles ["images/gallery/gal1"];
              let images'' = ...;
              let imageGallery = ...
                  imageGalleries = ...;
              .... }’

Also I have changed the version to >= 0.3 (otherwise it would already complain at trying to get a [Value] from copyFiles as well ) I have had to do some (ugly? ) fix for dependencies. I added allow-newer: true. It now also mentions : 

    WARNING: Ignoring out of range dependency (allow-newer enabled): Glob-0.7.14. sitepipe requires: >=0.8.0 && <0.9
    WARNING: Ignoring out of range dependency (allow-newer enabled): aeson-1.0.2.1. sitepipe requires: >=1.1.2.0 && <1.3
    WARNING: Ignoring out of range dependency (allow-newer enabled): lens-4.15.1. sitepipe requires: >=4.15.4 && <4.16
    WARNING: Ignoring out of range dependency (allow-newer enabled): lens-aeson-1.0.1. sitepipe requires: >=1.0.2 && <1.1
    WARNING: Ignoring out of range dependency (allow-newer enabled): megaparsec-5.2.0. sitepipe requires: >=5.3.1 && <6.3
    WARNING: Ignoring out of range dependency (allow-newer enabled): text-1.2.2.1. sitepipe requires: >=1.2.2.2 && <1.3
    WARNING: Ignoring out of range dependency (allow-newer enabled): yaml-0.8.22.1. sitepipe requires: >=0.8.23.3 && <0.9

**Comment by ChrisPenner** [comment]
Please read the Aeson docs for `fromJSON`; it returns a `Result a` type; you'll need to unpack the `Success` constructor (or handle the error case); You'll need to import `Data.Aeson` to gain access to the Result type and its constructors though.

Try something like this:

```haskell
import Data.Aeson
-- ...
imageList :: [Image]
imageList = case traverse fromJSON images' of
  Success imgs -> imgs
  Error err -> error "Do something to handle error here"
```

**Comment by ProofOfPizza** [comment]
Yes, that does it. Thank for bearing with me while I am learning!  :) 

For anyone coming here trying to learn like me, working exampe cam be found in the [AntiforZ](https://gitlab.com/AntiforZ.com/AntiforZ-site) repo.
