### ISSUE TITLE
Version bumps required

### ISSUE THREAD

**Issue by endgame** [ChrisPenner/SitePipe#18]
I am unable to build sitepipe on current nixpkgs because the versions of Glob, megaparsec, pandoc and lens are too new for sitepipe's stated version bounds in the `.cabal` flie.

I have read the changelogs of Glob, megaparsec and lens, and believe that it is safe to relax their upper bounds.

Pandoc is more complicated. Version 2.x has changed quite a lot, and I'm not familiar enough with the sitepipe internals to update it.

**Comment by ChrisPenner** [comment]
Feel free to submit a PR for bumping up the version constraints and I'd be happy to merge and publish it :)

As for Pandoc 2.0 it would be a lot of work to support it unfortunately; SitePipe isn't deprecrated, but I've been putting work into [Slick](https://github.com/ChrisPenner/Slick) instead lately, which is basically SitePipe but runs on the Shake build system, is more adaptable, and runs on Pandoc 2.0.

**Comment by endgame** [comment]
Funny story: when I saw that supporting the new pandoc would be nontrivial, I said "stuff it, time to learn shake". I'll have a look at slick.

In any case, I've pushed a PR to relax some upper bounds that should be safe (by changelog inspection).

**Comment by ChrisPenner** [comment]
Haha, glad I've got good timing!
