### ISSUE TITLE
Blockquotes in markdown gets compiled to <p> tags

### ISSUE THREAD

**Issue by MarcCoquand** [ChrisPenner/SitePipe#20]
Hey! Thanks for this fantastic library! I noticed that when in Markdown writing

```
> A quote
```
It compiles, in html, to
```
<p>A quote</p>
```
When it in fact should be 
```
<blockquote>A quote</blockquote>
```

**Comment by MarcCoquand** [comment]
Nvm, It creates a 
```
<blockquote><p>etc..</p></blockquote>
```

**Comment by ChrisPenner** [comment]
Haha, glad it worked out 😄

Sitepipe uses Pandoc for markdown rendering so it's unlikely there are significant issues, but if anything seems funny let me know ☺️
