### ISSUE TITLE
Indicate in README that this project has been superseded by slick

### ISSUE THREAD

**Issue by StevenXL** [ChrisPenner/SitePipe#23]
Issue #17 seems to suggest that [slick](https://github.com/ChrisPenner/slick) should be used instead of [SitePipe](https://github.com/ChrisPenner/SitePipe). I would like to suggest that we add this to the README.md.

**Comment by ChrisPenner** [comment]
Good call; I added a note. SitePipe can probably be deprecated in favour of slick in the future, but I'm not in any rush to do that ATM.

Thanks!
